pipeline:
    get-deps:
        image: docker:git
        when:
            event: push
            branch: master
        commands:
            - "git clone https://github.com/moe-serifu-circle/moe-serifu-circle.github.io public"

    generate:
        image: cbrgm/drone-hugo:0.40.2
        output: public
        validate: true
        when:
            event: push
            branch: master
    
    write-version:
        image: docker:git
        when:
            event: push
            branch: master
        commands:
            - "git log -1 --pretty=%B >> public/version-history.txt"
            - "echo ----------------------------------------------- >> public/version-history.txt"

    publish:
        image: appleboy/drone-git-push:latest
        branch: master
        path: public
        remote: "git@github.com:moe-serifu-circle/moe-serifu-circle.github.io"
        remote_name: 
        commit: true
        commit_message: "[drone] Added generated website"
        author_name: "MSC Service Account"
        author_email: "bot@moeserifu.moe"
        when:
            event: push
            branch: master
        secrets:
            - git_push_ssh_key
