baseURL = "http://www.moeserifu.moe"
languageCode = "en-us"
title = "Moe Serifu"
enableRobotsTXT = true
hasCJKLanguage = true

[taxonomies]
	tag = "tags"
	category = "categories"
	author = "authors"

[params]
	project = "Moe Serifu Agent"
	tagline = "Cuteness & Curiosity"

[[menu.main]]
	name = "Home"
	identifier = "home"
	url = "/"
	weight = 1
[[menu.main]]
	name = "Blog"
	identifier = "blog"
	url = "/posts/"
	weight = 2
[[menu.main]]
	name = "About"
	identifier = "about"
	url = "/about/"
	weight = 3
[[menu.main]]
	name = "Join the Crew"
	identifier = "join"
	url = "/join/"
	weight = 4